### ISSUE TITLE
Acquisition Terms Accepted!

### ISSUE THREAD

**Issue by TY-FOON** [TY-FOON/SEEKING-SOLDADA#1]
We have come to an agreement with aidevteam-icloud to provide outside software generation consulting to ensure plausible deniability.  We are excited about the opportunities over the next iteration of hardware technologies they will acquire!

**Comment by aidevteam-icloudcom** [comment]
We are excited to have you along for the ride TY-FOON!  Hopefully the bumpy weather is kept at bay.  Where the watermelons grow.

Make sure to run all of your source code through the DAST, SAST, and IAST techniques for malware analysis found at this [OWASP link](https://owasp.org/www-community/Free_for_Open_Source_Application_Security_Tools).  

Don't want to be drinking the kool-aid and having a liability from the single source if you know what we mean.  We don't care how in-depth* the cloud security is, not suitable methodology for our defenses*.  What department did you say you were from again?:  

*[Defense in Depth](https://csrc.nist.gov/glossary/term/defense_in_depth)
